# Generated by Django 6.1.1 on 2026-09-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
